FROM node:20-alpine

WORKDIR /usr/src/app

COPY client/package*.json ./

RUN npm install

COPY client/ ./

RUN npm run build

EXPOSE 5173

# Expose Vite dev server on host 0.0.0.0 for container accessibility
CMD ["npm", "run", "dev", "--", "--host"]
